//! Low-significant-bit (LSB) autocorrelation tests.
//!
//! Detects whether the lower bits of an integer recording carry independent
//! analog noise (true bit depth claimed) or deterministic filter residue
//! (DSP-padded from a lower-bit-depth ADC). See companion `pipistrelle`
//! module for hardware-specific reverse engineering of the latter case.
//!
//! Strategy:
//!  1. GCD/stride test catches zero-padded recordings (low N bits literally 0).
//!  2. On the quietest non-overlapping window of the file, run a chi-squared
//!     test of low N bits vs uniform and lag-1 / lag-256 autocorrelation of
//!     the low bits. Strong non-uniformity or autocorrelation indicates the
//!     LSBs were generated by DSP, not by sampling noise.
//!  3. If even the quietest window has too much analog noise, LSB tests are
//!     inconclusive — analog noise dithers any DSP signature into uniformity.

#[derive(Clone, Debug, PartialEq)]
pub enum LsbVerdict {
    /// Low N bits are literally zero across the *whole* file — N bits of
    /// zero-padding from a lower bit depth source (e.g. 12-bit ADC
    /// zero-extended into 16-bit container).
    ZeroPaddedNBit { effective_bits: u16, padding_bits: u16 },
    /// Low N bits are zero in *quiet* sections but used elsewhere — the
    /// recorder still has its full claimed bit depth, but its DSP /
    /// noise-gate / AGC chain stops feeding analog noise into the LSBs
    /// when the input level drops. Common signature for high-end
    /// recorders that aren't dithering (e.g. Pettersson D1000 family).
    QuietSectionZeroPadded {
        /// Effective bits in the quiet section (typically = nominal - padding_bits).
        effective_bits_in_quiet: u16,
        /// How many LSBs are zero in the quiet section.
        padding_bits: u16,
    },
    /// Low N bits are non-uniform and/or autocorrelated — filter residue
    /// from a deterministic DSP chain on top of a lower-bit-depth source.
    DspPaddedLowBitDepth { effective_bits_guess: u16 },
    /// Low bits look like analog noise; consistent with the claimed bit depth.
    ConsistentWithClaimedBitDepth,
    /// Quietest window's noise floor too high to discriminate. The DSP
    /// signature, if present, is dithered into uniformity by analog noise.
    Inconclusive,
    /// Float format, sample count too low, or other reason this test does
    /// not apply.
    NotApplicable,
}

#[derive(Clone, Debug, PartialEq)]
pub struct LsbAutocorrResult {
    pub verdict: LsbVerdict,
    pub explanation: String,
    /// Number of low bits inspected (typically 4).
    pub n_low: u16,
    /// Window length used for quietest-window analysis (samples).
    pub window_size: usize,
    /// GCD of nonzero |samples|. >=2 power-of-two => zero-padded.
    pub gcd_nonzero: u32,
    /// Index of the quietest non-overlapping window, in samples.
    pub quietest_window_idx: usize,
    /// Stdev of the quietest window, in integer LSB units (not normalized).
    pub quietest_window_stdev: f64,
    /// Fraction of samples in the quietest window with nonzero low N bits.
    /// Expected ~1 - 1/2^N (~93.75% for N=4) for uniform LSBs.
    pub quiet_lsb_nonzero_frac: f64,
    /// Chi-squared statistic of low N bits vs uniform, in the quietest
    /// window. df = 2^N - 1; critical value at p<0.001, df=15 ≈ 37.7.
    pub quiet_lsb_chi2: f64,
    /// Lag-1 autocorrelation of signed-centered low N bits, in the quietest
    /// window. ~0 for white noise; substantial for IIR filter residue.
    pub quiet_lsb_lag1_acf: f64,
    /// Long-lag autocorrelation (lag 256). Helps separate genuine IIR
    /// signatures (long-lag plateau) from short-range correlations.
    pub quiet_lsb_lag256_acf: f64,
    /// Smallest period over which the low N bits exactly repeat for ≥99%
    /// of samples in the quietest window. `None` if no periodic repetition
    /// is found within `MAX_PATTERN_PERIOD` samples (the typical case for
    /// dithered / random LSBs). Useful for surfacing "all 0s" (period 1)
    /// or short repeating noise patterns left behind by a fixed-output
    /// firmware DSP chain.
    pub low_bit_period: Option<usize>,
    /// Match rate at `low_bit_period` (1.0 = exact repetition). Only
    /// meaningful when `low_bit_period.is_some()`.
    pub low_bit_period_match: f64,
}

/// Default number of low bits to inspect. 4 matches the common
/// 12-bit-ADC-in-16-bit-container case (e.g. RP2040, many ultrasonic mics).
pub const DEFAULT_N_LOW: u16 = 4;

/// Default window size for quietest-window scan.
pub const DEFAULT_WINDOW: usize = 4096;

/// Maximum noise-floor stdev (in integer LSB) below which LSB tests are
/// considered conclusive. Above this, analog noise dithers out any DSP
/// signature. Tuned so that ~4 bits of dither (stdev ~16 LSB) is the cutoff.
const QUIET_STDEV_LIMIT: f64 = 16.0;

/// Chi-squared threshold for non-uniform LSBs. df=15; p<0.001 critical
/// value is ~37.7. We use a more conservative threshold to avoid
/// false-positives from large windows.
const CHI2_THRESHOLD: f64 = 200.0;

/// Autocorrelation magnitude threshold for "non-white" LSBs.
const ACF_THRESHOLD: f64 = 0.05;

/// Largest LSB-pattern period we search for. 512 covers the common DSP
/// pulse / step patterns; longer periods are not distinguishable from
/// random in a single 4096-sample window.
const MAX_PATTERN_PERIOD: usize = 512;
/// Minimum fraction of period-matched samples to accept a period as
/// "the" pattern length.
const PATTERN_MATCH_THRESHOLD: f64 = 0.99;

pub fn analyze_lsb_autocorr(
    samples: &[f32],
    bits_per_sample: u16,
    is_float: bool,
) -> LsbAutocorrResult {
    analyze_lsb_autocorr_opts(samples, bits_per_sample, is_float, DEFAULT_N_LOW, DEFAULT_WINDOW)
}

pub fn analyze_lsb_autocorr_opts(
    samples: &[f32],
    bits_per_sample: u16,
    is_float: bool,
    n_low: u16,
    window: usize,
) -> LsbAutocorrResult {
    let default = LsbAutocorrResult {
        verdict: LsbVerdict::NotApplicable,
        explanation: String::new(),
        n_low,
        window_size: window,
        gcd_nonzero: 1,
        quietest_window_idx: 0,
        quietest_window_stdev: 0.0,
        quiet_lsb_nonzero_frac: 0.0,
        quiet_lsb_chi2: 0.0,
        quiet_lsb_lag1_acf: 0.0,
        quiet_lsb_lag256_acf: 0.0,
        low_bit_period: None,
        low_bit_period_match: 0.0,
    };

    if is_float || bits_per_sample < n_low + 4 || samples.len() < window * 2 {
        return LsbAutocorrResult {
            explanation: if is_float {
                "Float format — LSB tests only meaningful for integer audio".into()
            } else if bits_per_sample < n_low + 4 {
                format!("Bit depth {} too low for {}-bit LSB analysis", bits_per_sample, n_low)
            } else {
                format!("Need at least {} samples", window * 2)
            },
            ..default
        };
    }

    let scale = (1u32 << (bits_per_sample - 1)) as f64;
    let ints: Vec<i32> = samples
        .iter()
        .map(|&s| (s as f64 * scale).round().clamp(i32::MIN as f64, i32::MAX as f64) as i32)
        .collect();

    let g = stride_gcd(&ints);
    if g >= 2 && g.is_power_of_two() {
        let pad = g.trailing_zeros() as u16;
        let pad = pad.min(bits_per_sample - 1);
        let eff = bits_per_sample.saturating_sub(pad);
        return LsbAutocorrResult {
            verdict: LsbVerdict::ZeroPaddedNBit { effective_bits: eff, padding_bits: pad },
            explanation: format!(
                "All nonzero samples are multiples of {} \u{2014} low {} bit{} literally zero",
                g, pad, if pad == 1 { "" } else { "s" }
            ),
            gcd_nonzero: g,
            // Period 1 = "all the same value" (zero, in this case).
            low_bit_period: Some(1),
            low_bit_period_match: 1.0,
            ..default
        };
    }

    // Skip a small warmup region (first ~1 window worth) to avoid filter startup transients.
    let warmup = window.min(ints.len() / 8);
    let (qi_rel, qsd) = find_quietest_window(&ints[warmup..], window);
    let qi = qi_rel + warmup;
    let seg = &ints[qi..qi + window];

    let mask = (1i32 << n_low) - 1;
    let bins = 1usize << n_low;

    // Low-bit histogram + chi-squared
    let mut hist = vec![0usize; bins];
    let mut nonzero = 0usize;
    for &v in seg {
        let lb = (v & mask) as usize;
        hist[lb] += 1;
        if lb != 0 { nonzero += 1; }
    }
    let nonzero_frac = nonzero as f64 / seg.len() as f64;
    let expected = seg.len() as f64 / bins as f64;
    let chi2: f64 = hist
        .iter()
        .map(|&c| {
            let d = c as f64 - expected;
            d * d / expected
        })
        .sum();

    let r1 = low_bit_acf(seg, 1, n_low);
    let r256 = if seg.len() > 512 { low_bit_acf(seg, 256, n_low) } else { 0.0 };
    let (period, period_match) = find_lsb_period(seg, n_low);

    let result = LsbAutocorrResult {
        verdict: LsbVerdict::ConsistentWithClaimedBitDepth, // placeholder
        explanation: String::new(),
        n_low,
        window_size: window,
        gcd_nonzero: g,
        quietest_window_idx: qi,
        quietest_window_stdev: qsd,
        quiet_lsb_nonzero_frac: nonzero_frac,
        quiet_lsb_chi2: chi2,
        quiet_lsb_lag1_acf: r1,
        quiet_lsb_lag256_acf: r256,
        low_bit_period: period,
        low_bit_period_match: period_match,
    };

    // First check the special case: the *quietest* window has all-zero
    // low N bits (period=1, near-100% match, qsd=0). This is the
    // "noise-gated quiet section" signature — typical of high-end
    // recorders like the Pettersson D1000 family, which still record at
    // their nominal bit depth in loud sections but emit literal zeros in
    // the low bits when the input drops below some threshold. The
    // whole-file GCD check fails here because loud sections do use the
    // full bit depth — only the quiet sections look 12-bit.
    let quiet_window_all_zero = period == Some(1)
        && period_match >= 0.999
        && qsd < 0.5  // window is essentially silent
        && nonzero_frac < 0.01;
    if quiet_window_all_zero {
        return LsbAutocorrResult {
            verdict: LsbVerdict::QuietSectionZeroPadded {
                effective_bits_in_quiet: bits_per_sample.saturating_sub(n_low),
                padding_bits: n_low,
            },
            explanation: format!(
                "Low {} bits are literally zero in the quietest window but used \
                 elsewhere \u{2014} the recorder still has its full claimed {}-bit \
                 depth, but its DSP / noise-gate / AGC stops dithering the LSBs \
                 when the signal drops",
                n_low, bits_per_sample,
            ),
            ..result
        };
    }

    // Check for DSP signature. If LSBs are non-uniform or autocorrelated
    // even with a noisy window, the structure is strong enough to detect
    // through the dither, so we should report it. Only fall back to
    // "Inconclusive" when LSBs *look* like noise but the floor is too high
    // for us to be sure they aren't deterministic.
    let dsp_signature = chi2 > CHI2_THRESHOLD
        || r1.abs() > ACF_THRESHOLD
        || r256.abs() > ACF_THRESHOLD;

    if dsp_signature {
        return LsbAutocorrResult {
            verdict: LsbVerdict::DspPaddedLowBitDepth {
                effective_bits_guess: bits_per_sample.saturating_sub(n_low),
            },
            explanation: format!(
                "Low {} bits show structure (chi\u{00B2}={:.0}, r\u{2081}={:+.3}, \
                 r\u{2082}\u{2085}\u{2086}={:+.3}) \u{2014} consistent with deterministic \
                 DSP residue on top of a ~{}-bit ADC",
                n_low, chi2, r1, r256, bits_per_sample - n_low
            ),
            ..result
        };
    }

    if qsd > QUIET_STDEV_LIMIT {
        return LsbAutocorrResult {
            verdict: LsbVerdict::Inconclusive,
            explanation: format!(
                "Quietest window's noise floor (stdev {:.1} LSB) exceeds {} \u{2014} \
                 analog noise dithers out any DSP signature, so LSB tests cannot \
                 distinguish DSP-padded from true {}-bit",
                qsd, QUIET_STDEV_LIMIT as i32, bits_per_sample
            ),
            ..result
        };
    }

    LsbAutocorrResult {
        verdict: LsbVerdict::ConsistentWithClaimedBitDepth,
        explanation: format!(
            "Low {} bits are uniform and uncorrelated in the quietest window \
             \u{2014} consistent with claimed {}-bit depth",
            n_low, bits_per_sample
        ),
        ..result
    }
}

/// GCD of |s| for nonzero s. Returns 1 if any sample is ±1, else the GCD.
fn stride_gcd(samples: &[i32]) -> u32 {
    let mut g: u32 = 0;
    for &v in samples {
        if v != 0 {
            g = gcd_u32(g, v.unsigned_abs());
            if g == 1 {
                return 1;
            }
        }
    }
    if g == 0 { 1 } else { g }
}

fn gcd_u32(a: u32, b: u32) -> u32 {
    if b == 0 { a } else { gcd_u32(b, a % b) }
}

fn find_quietest_window(samples: &[i32], window: usize) -> (usize, f64) {
    if samples.len() < window {
        return (0, 0.0);
    }
    let mut best_sd = f64::INFINITY;
    let mut best_i = 0usize;
    let mut i = 0;
    while i + window <= samples.len() {
        let seg = &samples[i..i + window];
        let mean: f64 = seg.iter().map(|&v| v as f64).sum::<f64>() / window as f64;
        let var: f64 = seg
            .iter()
            .map(|&v| {
                let d = v as f64 - mean;
                d * d
            })
            .sum::<f64>()
            / window as f64;
        let sd = var.sqrt();
        if sd < best_sd {
            best_sd = sd;
            best_i = i;
        }
        i += window;
    }
    (best_i, best_sd)
}

/// Search for the smallest period (in samples) at which the low `n_low`
/// bits of `seg` repeat identically for at least `PATTERN_MATCH_THRESHOLD`
/// of compared positions. Returns the period and the actual match rate.
/// Returns `None` if no period within `MAX_PATTERN_PERIOD` reaches the
/// threshold (the common dithered-noise case).
fn find_lsb_period(seg: &[i32], n_low: u16) -> (Option<usize>, f64) {
    let mask = (1i32 << n_low) - 1;
    let n = seg.len();
    if n < 4 { return (None, 0.0); }
    let max_p = MAX_PATTERN_PERIOD.min(n / 2);
    let mut best_period: Option<usize> = None;
    let mut best_match = 0.0f64;
    for p in 1..=max_p {
        let mut matches = 0usize;
        let mut compared = 0usize;
        for i in 0..(n - p) {
            if (seg[i] & mask) == (seg[i + p] & mask) {
                matches += 1;
            }
            compared += 1;
        }
        let rate = matches as f64 / compared as f64;
        if rate > best_match {
            best_match = rate;
        }
        if rate >= PATTERN_MATCH_THRESHOLD {
            best_period = Some(p);
            return (best_period, rate);
        }
    }
    (best_period, best_match)
}

fn low_bit_acf(seg: &[i32], lag: usize, n_low: u16) -> f64 {
    if seg.len() <= lag {
        return 0.0;
    }
    let mask = (1i32 << n_low) - 1;
    let half = 1i32 << (n_low - 1);
    // Map low bits to a signed-centered window so the mean isn't biased
    // toward (bins-1)/2 just because we're using unsigned bin indices.
    let x: Vec<f64> = seg
        .iter()
        .map(|&v| (((v & mask) ^ half) - half) as f64)
        .collect();
    let mean: f64 = x.iter().sum::<f64>() / x.len() as f64;
    let xc: Vec<f64> = x.iter().map(|&v| v - mean).collect();
    let var: f64 = xc.iter().map(|&v| v * v).sum::<f64>() / xc.len() as f64;
    if var == 0.0 {
        return 0.0;
    }
    let n = xc.len() - lag;
    let acc: f64 = (0..n).map(|i| xc[i] * xc[i + lag]).sum();
    acc / (n as f64 * var)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn to_f32(ints: &[i32], bits: u16) -> Vec<f32> {
        let scale = (1u32 << (bits - 1)) as f32;
        ints.iter().map(|&v| v as f32 / scale).collect()
    }

    #[test]
    fn float_input_returns_not_applicable() {
        let samples = vec![0.5f32; 16384];
        let r = analyze_lsb_autocorr(&samples, 32, true);
        assert!(matches!(r.verdict, LsbVerdict::NotApplicable));
    }

    #[test]
    fn zero_padded_12_in_16_detected() {
        // Synthesize: every sample is a multiple of 16
        let ints: Vec<i32> = (0..16384).map(|i| ((i as i32 * 37) & 0x7F0) - 1024).collect();
        let samples = to_f32(&ints, 16);
        let r = analyze_lsb_autocorr(&samples, 16, false);
        match r.verdict {
            LsbVerdict::ZeroPaddedNBit { effective_bits, padding_bits } => {
                assert_eq!(padding_bits, 4);
                assert_eq!(effective_bits, 12);
            }
            other => panic!("expected ZeroPadded, got {:?}", other),
        }
    }

    #[test]
    fn random_lsbs_classified_as_true_bit_depth() {
        // Pseudo-random LSBs (linear congruential) on top of small signal
        let mut state: u32 = 12345;
        let ints: Vec<i32> = (0..32768)
            .map(|_| {
                state = state.wrapping_mul(1664525).wrapping_add(1013904223);
                // Tiny signal range so chi-squared isn't dominated by signal shape
                ((state >> 16) & 0x3F) as i32 - 32
            })
            .collect();
        let samples = to_f32(&ints, 16);
        let r = analyze_lsb_autocorr(&samples, 16, false);
        // Should be consistent or inconclusive — definitely not DspPadded
        assert!(
            !matches!(r.verdict, LsbVerdict::DspPaddedLowBitDepth { .. }),
            "false DSP-padded verdict on white-noise input: {:?}",
            r
        );
    }

    #[test]
    fn iir_residue_in_lsbs_detected() {
        // Synthesize a constant input through a fake IIR-style accumulator
        // that drips deterministic LSB content. This mimics the pipistrelle
        // HPF: an accumulator that affects only the low bits.
        let mut acc: i32 = 0;
        let ints: Vec<i32> = (0..16384)
            .map(|i| {
                // Tiny ramp signal in upper bits, IIR drip in low bits
                acc = acc.wrapping_add(1);
                let sig = (i as i32 / 1024) - 8;            // upper-bit signal
                let lsb = (acc * 37) & 0xF;                  // deterministic low bits
                (sig << 4) | lsb
            })
            .collect();
        let samples = to_f32(&ints, 16);
        let r = analyze_lsb_autocorr(&samples, 16, false);
        // The deterministic low bits should make r1 or chi2 light up
        assert!(
            matches!(r.verdict, LsbVerdict::DspPaddedLowBitDepth { .. }),
            "expected DspPadded verdict, got {:?}",
            r
        );
    }
}
